package com.riviu.agent;

import android.content.Context;
import android.util.Log;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.TimeUnit;
import java.util.UUID;

/**
 * Loopback HTTP/1.1 for the helper protocol, authenticated with a shared token.
 *
 * <p>Binding 127.0.0.1 is necessary and <b>not sufficient</b>. On Android, loopback is not a
 * permission boundary: {@code INTERNET} is a normal, auto-granted permission, so any app on the
 * phone — including one that asked for nothing — can connect to this port. Before the token,
 * that meant every endpoint below was public to the whole device: read the clipboard, delete any
 * photo, open any file as a wallpaper, spoof GPS.
 *
 * <p>The token is generated by the desktop and handed to the service at start; it lives in
 * process memory and never touches disk. Every request must carry it in {@code X-Riviu-Token},
 * with {@code GET /status} the single exception so the host can still identify a helper it has
 * not yet been given a token for. The same shape the iOS agent has used all along.
 */
final class HttpServer {
    private static final String TAG = "RiviuHelper";
    /** Header the shared token travels in. */
    static final String TOKEN_HEADER = "X-Riviu-Token";
    /** Longest a single header line may be, and how many of them one request may send. */
    private static final int MAX_HEADER_LINES = 64;
    /** Concurrent requests. Small: the host talks to one phone at a time, but a single thread
     * meant one slow or hostile caller froze the helper for everyone, including the desktop. */
    private static final int WORKER_THREADS = 4;

    private final Context context;
    private final int port;
    private final String token;
    private volatile boolean running;
    private volatile ServerSocket server;
    private volatile Thread thread;
    private final OwnedRequests workers = new OwnedRequests(WORKER_THREADS, 8);
    private final ClipboardStore clipboard;
    private final String serviceInstance;
    private final String ownerId;
    private final String ownerGeneration;
    private boolean closing;

    HttpServer(Context context, int port, String token) {
        this(context, port, token, UUID.randomUUID().toString(), null, null);
    }
    HttpServer(Context context, int port, String token, String instance, String owner, String generation) {
        this.serviceInstance = instance;
        this.ownerId = owner;
        this.ownerGeneration = generation;
        this.context = context.getApplicationContext();
        this.port = port;
        this.token = token == null ? "" : token;
        this.clipboard = new ClipboardStore(this.context);
    }

    synchronized void start() throws IOException {
        if (running) {
            return;
        }
        if (closing) throw new IOException("server closing");
        server = new ServerSocket(port, 8, InetAddress.getByName("127.0.0.1"));
        server.setSoTimeout(1000);
        running = true;
        thread = new Thread(this::acceptLoop, "riviu-helper-http");
        thread.start();
    }

    synchronized void stop() {
        if (closing) return;
        closing = true;
        running = false;
        if (server != null) {
            try { server.close(); } catch (IOException ignored) {}
        }
        clipboard.closeAdmission();
        workers.closeAdmission();
        // No main-looper await: clipboard effects need that same looper to settle.
        Thread drain = new Thread(() -> {
            try {
                if (!workers.awaitDrain(10, TimeUnit.SECONDS) || clipboard.unsettled() != 0) {
                    Log.w(TAG, "HTTP drain remains unsettled; replacement must stay blocked");
                }
            } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
        }, "riviu-helper-drain");
        drain.start();
    }

    boolean hasOutstandingWork() {
        return workers.ownedCount() != 0 || clipboard.unsettled() != 0;
    }
    boolean awaitSettlement(long timeout, TimeUnit unit) throws InterruptedException {
        long deadline = System.nanoTime() + unit.toNanos(timeout);
        if (!workers.awaitDrain(timeout, unit)) return false;
        while (clipboard.unsettled() != 0) {
            if (System.nanoTime() - deadline >= 0) return false;
            Thread.sleep(10); // Only the dedicated release worker waits, never Android main.
        }
        return true;
    }

    synchronized boolean isRunning() {
        return running && server != null && !server.isClosed()
                && thread != null && thread.isAlive();
    }

    private void acceptLoop() {
        while (running) {
            try {
                Socket socket = server.accept();
                // Served on a worker, not here. On the accept thread, one caller dribbling a
                // byte every few seconds held the *only* thread and the helper went dark for
                // the desktop too — a denial of service that cost the attacker nothing.
                workers.accept(socket, () -> {
                    try { handle(socket); }
                    catch (IOException error) { Log.w(TAG, "connection failed"); }
                });
            } catch (SocketTimeoutException ignored) {
            } catch (IOException error) {
                if (running) Log.w(TAG, "accept failed");
                running = false;
                break;
            }
        }
    }

    private void handle(Socket socket) throws IOException {
        socket.setSoTimeout(5000);
        InputStream raw = new BufferedInputStream(socket.getInputStream());
        OutputStream out = new BufferedOutputStream(socket.getOutputStream());
        String requestLine = readLine(raw);
        if (requestLine == null || requestLine.isEmpty()) {
            return;
        }
        String[] parts = requestLine.split(" ");
        if (parts.length < 2) {
            writeQuiet(out, 400, "bad_request", "request line is not HTTP");
            return;
        }
        String method = parts[0];
        String path = parts[1];
        int contentLength = 0;
        String presented = null;
        // Bounded: the loop used to be `while (true)` with no cap on how many header lines one
        // request could send, so a caller could feed headers forever inside the read timeout.
        for (int line = 0; line <= MAX_HEADER_LINES; line++) {
            if (line == MAX_HEADER_LINES) {
                writeQuiet(out, 431, "too_many_headers", "header count exceeds " + MAX_HEADER_LINES);
                return;
            }
            String header = readLine(raw);
            if (header == null || header.isEmpty()) {
                break;
            }
            int colon = header.indexOf(':');
            if (colon < 0) {
                continue;
            }
            String name = header.substring(0, colon).trim();
            String value = header.substring(colon + 1).trim();
            if (name.equalsIgnoreCase("Content-Length")) {
                try {
                    contentLength = Integer.parseInt(value);
                } catch (NumberFormatException ignored) {
                    contentLength = -1;
                }
            } else if (name.equalsIgnoreCase(TOKEN_HEADER)) {
                presented = value;
            }
        }
        // Before the body is read, and before anything is routed: an unauthorised caller must
        // not be able to make the helper allocate, let alone act. `GET /status` is exempt so the
        // host can still recognise a helper it has not yet handed a token to.
        if (!RequestAuth.allowed(method, path, token, presented)) {
            writeQuiet(out, 401, "unauthorized", "missing or wrong " + TOKEN_HEADER);
            return;
        }
        if (contentLength < 0 || contentLength > Protocol.MAX_BODY_BYTES) {
            writeQuiet(out, 413, "too_large", "body exceeds " + Protocol.MAX_BODY_BYTES);
            return;
        }
        byte[] body = readExact(raw, contentLength);
        try {
            JSONObject response = route(method, path, body);
            write(out, response.optBoolean("ok", false) ? 200 : 400, response);
        } catch (MainThreadJobs.Pending pending) {
            try {
                write(out, 409, Protocol.error(pending.state == MainThreadJobs.State.CANCELLED
                        ? "clipboard_cancelled" : "settlement_required", "query operation settlement")
                        .put("operationId", pending.operationId).put("serviceInstance", serviceInstance)
                        .put("state", pending.state.name().toLowerCase(java.util.Locale.ROOT)));
            } catch (Exception ignored) {}
        } catch (IllegalArgumentException error) {
            try {
                write(out, 400, Protocol.error("invalid_argument", error.getMessage()));
            } catch (Exception ignored) {
            }
        } catch (Exception error) {
            Log.w(TAG, "route failed");
            try {
                write(out, 500, Protocol.error("internal", "request failed; do not replay an effect"));
            } catch (Exception ignored) {
            }
        }
    }

    /**
     * Constant-time token comparison.
     *
     * <p>{@code String.equals} returns on the first differing byte, and this port answers at
     * loopback speed — a caller on the phone can retry as fast as it likes, so a comparison that
     * leaks where the mismatch fell leaks the token.
     *
     * <p>An empty configured token denies everything except {@code /status}. That is the safe
     * direction: a helper started without a token is inert rather than open.
     */
    private boolean tokenMatches(String presented) {
        return RequestAuth.tokenMatches(token, presented);
    }

    private JSONObject route(String method, String path, byte[] body) throws Exception {
        if ("GET".equals(method) && "/status".equals(path)) {
            return Protocol.status();
        }
        JSONObject json = body.length == 0 ? new JSONObject() : new JSONObject(new String(body, StandardCharsets.UTF_8));
        if ("POST".equals(method) && "/v1/session/status".equals(path)) {
            String nonce = json.optString("nonce", "");
            RequestAuth.requireId(nonce);
            return Protocol.ok().put("nonce", nonce).put("serviceInstance", serviceInstance)
                    .put("protocolVersion", Protocol.PROTOCOL_VERSION)
                    .put("ownership", ownerId == null ? "legacy_unproven" : "owned")
                    .put("ownerId", ownerId == null ? JSONObject.NULL : ownerId)
                    .put("ownerGeneration", ownerGeneration == null ? JSONObject.NULL : ownerGeneration)
                    .put("secureBootstrapAvailable", true).put("secureBootstrapQualified", false);
        }
        if ("POST".equals(method) && path.startsWith("/v1/clipboard/jobs/")) {
            return clipboardJob(path, json);
        }
        if ("POST".equals(method) && "/v1/clipboard/set".equals(path)) {
            clipboard.submit(null, true, json.optString("text", "")).await(5, TimeUnit.SECONDS);
            return Protocol.ok();
        }
        if ("POST".equals(method) && "/v1/clipboard/get".equals(path)) {
            ClipboardStore.Value value = clipboard.submit(null, false, null).await(5, TimeUnit.SECONDS);
            if (!value.available) return Protocol.error("clipboard_unavailable", "clipboard is not readable");
            return Protocol.ok().put("available", true).put("text", value.text);
        }
        if ("POST".equals(method) && "/v1/media/import".equals(path)) {
            return MediaStoreImport.importFile(
                    context,
                    json.optString("relativePath", ""),
                    json.optString("displayName", ""));
        }
        if ("POST".equals(method) && "/v1/wallpaper/set".equals(path)) {
            return WallpaperSet.setFromFile(context, json.optString("path", ""));
        }
        if ("POST".equals(method) && "/v1/location/set".equals(path)) {
            return MockLocation.set(context, json.optDouble("lat", 0), json.optDouble("lng", 0));
        }
        if ("POST".equals(method) && "/v1/location/stop".equals(path)) {
            return MockLocation.stop(context);
        }
        if ("POST".equals(method) && "/v1/apps/describe".equals(path)) {
            return AppList.describe(
                    context,
                    json.optJSONArray("packages"),
                    json.optBoolean("icons", true),
                    json.optInt("iconPx", 0));
        }
        return Protocol.error("not_found", method + " " + path);
    }

    private JSONObject clipboardJob(String path, JSONObject json) throws Exception {
        if (!serviceInstance.equals(json.optString("serviceInstance", ""))) {
            return Protocol.error("instance_mismatch", "service instance changed; reconcile, do not replay");
        }
        String id = json.optString("requestId", "");
        RequestAuth.requireId(id);
        MainThreadJobs.Job<?> job;
        if ("/v1/clipboard/jobs/submit".equals(path)) {
            String action = json.optString("action", "");
            boolean set = "set".equals(action);
            boolean compare = "compareSet".equals(action);
            boolean snapshot = "snapshot".equals(action);
            boolean restore = "restoreSnapshot".equals(action);
            if (!set && !compare && !snapshot && !restore && !"get".equals(action)) throw new IllegalArgumentException("invalid clipboard action");
            if ((set || compare) && !(json.opt("text") instanceof String)) {
                throw new IllegalArgumentException("write requires text string");
            }
            if ((compare || restore) && !(json.opt("expectedText") instanceof String)) {
                throw new IllegalArgumentException("conditional restore requires expectedText string");
            }
            if (restore && !(json.opt("baselineId") instanceof String)) throw new IllegalArgumentException("restore requires baselineId");
            try {
                if (snapshot) job = clipboard.snapshot(id);
                else if (restore) job = clipboard.restoreSnapshot(id, json.getString("baselineId"), json.getString("expectedText"));
                else if (compare) job = clipboard.compareSet(id, json.getString("expectedText"), json.getString("text"));
                else job = clipboard.submit(id, set, set ? json.getString("text") : null);
            }
            catch (IllegalStateException e) {
                return Protocol.error("clipboard_ledger_full", "clipboard admission unavailable");
            }
        } else if ("/v1/clipboard/jobs/status".equals(path)
                || "/v1/clipboard/jobs/cancelQueued".equals(path)) {
            job = clipboard.find(id);
            if (job == null) return Protocol.error("operation_unknown", "settlement unknown; do not replay");
        } else return Protocol.error("not_found", "unknown clipboard job endpoint");
        boolean cancel = "/v1/clipboard/jobs/cancelQueued".equals(path);
        boolean cancelled = cancel && job.cancelQueued();
        JSONObject response = Protocol.ok().put("serviceInstance", serviceInstance).put("operationId", job.id);
        synchronized (job) {
            MainThreadJobs.State state = job.state();
            response.put("state", state.name().toLowerCase(java.util.Locale.ROOT));
            if (cancel) response.put("cancelled", cancelled || state == MainThreadJobs.State.CANCELLED)
                    .put("settlementRequired", state == MainThreadJobs.State.RUNNING);
            if (state == MainThreadJobs.State.SUCCEEDED) {
                ClipboardStore.Value value = (ClipboardStore.Value) job.result();
                JSONObject result = new JSONObject();
                if (value.comparison != null) {
                    result.put("written", value.comparison.written).put("changed", value.comparison.changed)
                            .put("available", value.comparison.available).put("verified", value.comparison.verified);
                } else if (value.written) result.put("written", true);
                else {
                    result.put("available", value.available).put("plainTextBaseline", value.plainTextBaseline);
                    if (value.available) result.put("text", value.text);
                    if (value.baselineId != null) result.put("baselineId", value.baselineId);
                }
                response.put("result", result);
            } else if (state == MainThreadJobs.State.FAILED) response.put("error", "clipboard_failed");
        }
        return response;
    }

    private static void write(OutputStream out, int status, JSONObject json) throws Exception {
        byte[] payload = json.toString().getBytes(StandardCharsets.UTF_8);
        String reason = status == 200 ? "OK" : "Error";
        String header = "HTTP/1.1 " + status + " " + reason + "\r\n"
                + "Content-Type: application/json; charset=utf-8\r\n"
                + "Content-Length: " + payload.length + "\r\n"
                + "Connection: close\r\n\r\n";
        out.write(header.getBytes(StandardCharsets.US_ASCII));
        out.write(payload);
        out.flush();
    }

    private static void writeQuiet(OutputStream out, int status, String code, String message) {
        try {
            write(out, status, Protocol.error(code, message));
        } catch (Exception ignored) {
        }
    }

    private static String readLine(InputStream in) throws IOException {
        ByteArrayOutputStream line = new ByteArrayOutputStream();
        int previous = -1;
        while (true) {
            int next = in.read();
            if (next < 0) {
                if (line.size() == 0) {
                    return null;
                }
                break;
            }
            if (next == '\n') {
                break;
            }
            if (previous == '\r' && next != '\n') {
                line.write(previous);
            }
            if (next != '\r') {
                line.write(next);
            }
            previous = next;
            if (line.size() > 8192) {
                throw new IOException("header line exceeds 8192 bytes");
            }
        }
        return new String(line.toByteArray(), StandardCharsets.US_ASCII);
    }

    private static byte[] readExact(InputStream in, int length) throws IOException {
        byte[] body = new byte[length];
        int offset = 0;
        while (offset < length) {
            int read = in.read(body, offset, length - offset);
            if (read < 0) {
                throw new IOException("body ended after " + offset + " of " + length);
            }
            offset += read;
        }
        return body;
    }
}
