package com.riviu.agent;

import android.content.Context;
import android.util.Log;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 * Loopback HTTP/1.1 for the helper protocol, authenticated with a shared token.
 *
 * <p>Binding 127.0.0.1 is necessary and <b>not sufficient</b>. On Android, loopback is not a
 * permission boundary: {@code INTERNET} is a normal, auto-granted permission, so any app on the
 * phone — including one that asked for nothing — can connect to this port. Before the token,
 * that meant every endpoint below was public to the whole device: read the clipboard, delete any
 * photo, open any file as a wallpaper, spoof GPS.
 *
 * <p>The token is generated by the desktop and handed to the service at start; it lives in
 * process memory and never touches disk. Every request must carry it in {@code X-Riviu-Token},
 * with {@code GET /status} the single exception so the host can still identify a helper it has
 * not yet been given a token for. The same shape the iOS agent has used all along.
 */
final class HttpServer {
    private static final String TAG = "RiviuHelper";
    /** Header the shared token travels in. */
    static final String TOKEN_HEADER = "X-Riviu-Token";
    /** Longest a single header line may be, and how many of them one request may send. */
    private static final int MAX_HEADER_LINES = 64;
    /** Concurrent requests. Small: the host talks to one phone at a time, but a single thread
     * meant one slow or hostile caller froze the helper for everyone, including the desktop. */
    private static final int WORKER_THREADS = 4;

    private final Context context;
    private final int port;
    private final String token;
    private volatile boolean running;
    private ServerSocket server;
    private Thread thread;
    private ExecutorService workers;

    HttpServer(Context context, int port, String token) {
        this.context = context.getApplicationContext();
        this.port = port;
        this.token = token == null ? "" : token;
    }

    synchronized void start() throws IOException {
        if (running) {
            return;
        }
        server = new ServerSocket(port, 8, InetAddress.getByName("127.0.0.1"));
        server.setSoTimeout(1000);
        running = true;
        workers = Executors.newFixedThreadPool(WORKER_THREADS);
        thread = new Thread(this::acceptLoop, "riviu-helper-http");
        thread.start();
    }

    synchronized void stop() {
        running = false;
        if (server != null) {
            try {
                server.close();
            } catch (IOException ignored) {
            }
            server = null;
        }
        if (thread != null) {
            thread.interrupt();
            thread = null;
        }
        if (workers != null) {
            workers.shutdownNow();
            try {
                workers.awaitTermination(2, TimeUnit.SECONDS);
            } catch (InterruptedException ignored) {
                Thread.currentThread().interrupt();
            }
            workers = null;
        }
    }

    private void acceptLoop() {
        while (running) {
            try {
                Socket socket = server.accept();
                // Served on a worker, not here. On the accept thread, one caller dribbling a
                // byte every few seconds held the *only* thread and the helper went dark for
                // the desktop too — a denial of service that cost the attacker nothing.
                ExecutorService pool = workers;
                if (pool == null) {
                    socket.close();
                    continue;
                }
                pool.execute(() -> {
                    try {
                        handle(socket);
                    } catch (IOException error) {
                        Log.w(TAG, "connection failed", error);
                    } finally {
                        try {
                            socket.close();
                        } catch (IOException ignored) {
                        }
                    }
                });
            } catch (SocketTimeoutException ignored) {
            } catch (IOException error) {
                if (running) {
                    Log.w(TAG, "accept failed", error);
                }
            }
        }
    }

    private void handle(Socket socket) throws IOException {
        socket.setSoTimeout(5000);
        InputStream raw = new BufferedInputStream(socket.getInputStream());
        OutputStream out = new BufferedOutputStream(socket.getOutputStream());
        String requestLine = readLine(raw);
        if (requestLine == null || requestLine.isEmpty()) {
            return;
        }
        String[] parts = requestLine.split(" ");
        if (parts.length < 2) {
            writeQuiet(out, 400, "bad_request", "request line is not HTTP");
            return;
        }
        String method = parts[0];
        String path = parts[1];
        int contentLength = 0;
        String presented = null;
        // Bounded: the loop used to be `while (true)` with no cap on how many header lines one
        // request could send, so a caller could feed headers forever inside the read timeout.
        for (int line = 0; line <= MAX_HEADER_LINES; line++) {
            if (line == MAX_HEADER_LINES) {
                writeQuiet(out, 431, "too_many_headers", "header count exceeds " + MAX_HEADER_LINES);
                return;
            }
            String header = readLine(raw);
            if (header == null || header.isEmpty()) {
                break;
            }
            int colon = header.indexOf(':');
            if (colon < 0) {
                continue;
            }
            String name = header.substring(0, colon).trim();
            String value = header.substring(colon + 1).trim();
            if (name.equalsIgnoreCase("Content-Length")) {
                try {
                    contentLength = Integer.parseInt(value);
                } catch (NumberFormatException ignored) {
                    contentLength = -1;
                }
            } else if (name.equalsIgnoreCase(TOKEN_HEADER)) {
                presented = value;
            }
        }
        // Before the body is read, and before anything is routed: an unauthorised caller must
        // not be able to make the helper allocate, let alone act. `GET /status` is exempt so the
        // host can still recognise a helper it has not yet handed a token to.
        boolean statusProbe = "GET".equals(method) && "/status".equals(path);
        if (!statusProbe && !tokenMatches(presented)) {
            writeQuiet(out, 401, "unauthorized", "missing or wrong " + TOKEN_HEADER);
            return;
        }
        if (contentLength < 0 || contentLength > Protocol.MAX_BODY_BYTES) {
            writeQuiet(out, 413, "too_large", "body exceeds " + Protocol.MAX_BODY_BYTES);
            return;
        }
        byte[] body = readExact(raw, contentLength);
        try {
            JSONObject response = route(method, path, body);
            write(out, response.optBoolean("ok", false) ? 200 : 400, response);
        } catch (IllegalArgumentException error) {
            try {
                write(out, 400, Protocol.error("invalid_argument", error.getMessage()));
            } catch (Exception ignored) {
            }
        } catch (Exception error) {
            Log.w(TAG, "route failed", error);
            try {
                write(out, 500, Protocol.error("internal", String.valueOf(error.getMessage())));
            } catch (Exception ignored) {
            }
        }
    }

    /**
     * Constant-time token comparison.
     *
     * <p>{@code String.equals} returns on the first differing byte, and this port answers at
     * loopback speed — a caller on the phone can retry as fast as it likes, so a comparison that
     * leaks where the mismatch fell leaks the token.
     *
     * <p>An empty configured token denies everything except {@code /status}. That is the safe
     * direction: a helper started without a token is inert rather than open.
     */
    private boolean tokenMatches(String presented) {
        if (token.isEmpty() || presented == null) {
            return false;
        }
        return MessageDigest.isEqual(
                presented.getBytes(StandardCharsets.UTF_8), token.getBytes(StandardCharsets.UTF_8));
    }

    private JSONObject route(String method, String path, byte[] body) throws Exception {
        if ("GET".equals(method) && "/status".equals(path)) {
            return Protocol.status();
        }
        JSONObject json = body.length == 0 ? new JSONObject() : new JSONObject(new String(body, StandardCharsets.UTF_8));
        if ("POST".equals(method) && "/v1/clipboard/set".equals(path)) {
            ClipboardStore.setText(context, json.optString("text", ""));
            return Protocol.ok();
        }
        if ("POST".equals(method) && "/v1/clipboard/get".equals(path)) {
            return Protocol.ok().put("text", ClipboardStore.getText(context));
        }
        if ("POST".equals(method) && "/v1/media/import".equals(path)) {
            return MediaStoreImport.importFile(
                    context,
                    json.optString("relativePath", ""),
                    json.optString("displayName", ""));
        }
        if ("POST".equals(method) && "/v1/wallpaper/set".equals(path)) {
            return WallpaperSet.setFromFile(context, json.optString("path", ""));
        }
        if ("POST".equals(method) && "/v1/location/set".equals(path)) {
            return MockLocation.set(context, json.optDouble("lat", 0), json.optDouble("lng", 0));
        }
        if ("POST".equals(method) && "/v1/location/stop".equals(path)) {
            return MockLocation.stop(context);
        }
        if ("POST".equals(method) && "/v1/apps/describe".equals(path)) {
            return AppList.describe(
                    context,
                    json.optJSONArray("packages"),
                    json.optBoolean("icons", true),
                    json.optInt("iconPx", 0));
        }
        return Protocol.error("not_found", method + " " + path);
    }

    private static void write(OutputStream out, int status, JSONObject json) throws Exception {
        byte[] payload = json.toString().getBytes(StandardCharsets.UTF_8);
        String reason = status == 200 ? "OK" : "Error";
        String header = "HTTP/1.1 " + status + " " + reason + "\r\n"
                + "Content-Type: application/json; charset=utf-8\r\n"
                + "Content-Length: " + payload.length + "\r\n"
                + "Connection: close\r\n\r\n";
        out.write(header.getBytes(StandardCharsets.US_ASCII));
        out.write(payload);
        out.flush();
    }

    private static void writeQuiet(OutputStream out, int status, String code, String message) {
        try {
            write(out, status, Protocol.error(code, message));
        } catch (Exception ignored) {
        }
    }

    private static String readLine(InputStream in) throws IOException {
        ByteArrayOutputStream line = new ByteArrayOutputStream();
        int previous = -1;
        while (true) {
            int next = in.read();
            if (next < 0) {
                if (line.size() == 0) {
                    return null;
                }
                break;
            }
            if (next == '\n') {
                break;
            }
            if (previous == '\r' && next != '\n') {
                line.write(previous);
            }
            if (next != '\r') {
                line.write(next);
            }
            previous = next;
            if (line.size() > 8192) {
                throw new IOException("header line exceeds 8192 bytes");
            }
        }
        return new String(line.toByteArray(), StandardCharsets.US_ASCII);
    }

    private static byte[] readExact(InputStream in, int length) throws IOException {
        byte[] body = new byte[length];
        int offset = 0;
        while (offset < length) {
            int read = in.read(body, offset, length - offset);
            if (read < 0) {
                throw new IOException("body ended after " + offset + " of " + length);
            }
            offset += read;
        }
        return body;
    }
}
