import { openOperatorPage } from "./fixtures/operatorNavigation";
import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { installTauriMock, mockCommandCalls } from "./fixtures/tauriMock";

test("nurture compact scope and machine picker preserve drafts at three viewports", async ({ page }) => {
  await installTauriMock(page, { androidRoster: true, fleetSize: 38 });
  await page.goto("/");
  await openOperatorPage(page, "Nuôi TikTok");
  const workspace = page.getByRole("region", { name: "Không gian Nuôi TikTok" });
  const choose = workspace.getByRole("button", { name: "Chọn máy", exact: true });
  const picker = workspace.getByRole("dialog", { name: "Chọn máy Nuôi TikTok" });
  const machines = picker.getByRole("group", { name: "Danh sách chọn máy Nuôi TikTok" });
  await expect(workspace.getByRole("button", { name: /Cân bằng/ })).toHaveCount(0);
  await expect(workspace.getByText("Tuỳ chỉnh nâng cao", { exact: true })).toHaveCount(0);
  await workspace.getByLabel("Nguồn video").selectOption("search");
  await workspace.getByLabel("Từ khóa tìm kiếm").fill("đà lạt");
  await choose.click();
  await picker.getByRole("button", { name: "Chọn tất cả sẵn sàng", exact: true }).click();
  await expect(machines.getByRole("checkbox")).toHaveCount(38);
  await expect(machines.getByRole("checkbox", { checked: true })).toHaveCount(38);
  await expect(picker.getByRole("button", { name: "Trang máy tiếp" })).toHaveCount(0);
  await picker.getByRole("button", { name: "Xong", exact: true }).click();
  await expect(choose).toBeFocused();
  await expect(workspace.getByRole("tablist", { name: "Chế độ Nuôi TikTok" }).getByRole("tab")).toHaveText(["Thiết lập", "Hẹn giờ", "Theo dõi"]);
  const scope = workspace.getByRole("combobox", { name: "Phạm vi thiết bị", exact: true });
  await expect(scope).toHaveCount(1);
  await expect(scope.locator("option:checked")).toHaveText("38 máy đã chọn");
  const total = workspace.getByRole("spinbutton", { name: "Tổng số video muốn lướt", exact: true });
  await expect(total).toBeVisible();
  await expect(workspace.getByLabel("Giới hạn video", { exact: true })).toHaveCount(0);
  await expect(workspace.getByRole("spinbutton", { name: "Vòng", exact: true })).toHaveCount(0);
  await total.fill("75");
  await expect(workspace.getByRole("spinbutton", { name: /Thời lượng tối đa/ })).toHaveValue("30");
  expect((await new AxeBuilder({ page }).include(".nurture-workspace").withTags(["wcag2a", "wcag2aa"]).analyze()).violations).toEqual([]);
  for (const viewport of [{ width: 1440, height: 900 }, { width: 900, height: 900 }, { width: 820, height: 560 }]) {
    await page.setViewportSize(viewport);
    await choose.click();
    expect(await machines.evaluate(element => getComputedStyle(element).gridTemplateColumns.split(" ").length)).toBe(2);
    await expect(machines.getByRole("checkbox", { checked: true })).toHaveCount(38);
    await machines.getByRole("checkbox").last().scrollIntoViewIfNeeded();
    await expect(machines.getByRole("checkbox").last()).toBeInViewport();
    expect(await picker.evaluate(element => {
      const grid = element.querySelector(".nurture-machine-grid")!;
      const footer = element.querySelector(".detail-drawer-footer")!.getBoundingClientRect();
      return { gridScrolls: grid.scrollHeight > grid.clientHeight, footerFits: footer.bottom <= innerHeight, gridAboveFooter: grid.getBoundingClientRect().bottom <= footer.top };
    })).toEqual({ gridScrolls: true, footerFits: true, gridAboveFooter: true });
    await page.screenshot({ path: test.info().outputPath(`nurture-picker-${viewport.width}.png`) });
    await page.keyboard.press("Escape");
    await expect(picker).toHaveCount(0);
    await expect(choose).toBeFocused();
    const summary = workspace.getByRole("complementary", { name: "Tóm tắt phiên nuôi" });
    await summary.scrollIntoViewIfNeeded();
    await expect(summary).toBeInViewport();
    await expect(summary).toContainText("75 video · 30 phút");
    expect(await workspace.evaluate(element => {
      const footer = element.querySelector(".nurture-session-footer")!.getBoundingClientRect();
      const setup = element.querySelector("#nurture-page-panel-setup")!.getBoundingClientRect();
      return { horizontal: document.documentElement.scrollWidth <= innerWidth, footerFits: footer.bottom <= innerHeight, formAboveFooter: setup.bottom <= footer.top };
    })).toEqual({ horizontal: true, footerFits: true, formAboveFooter: true });
    await total.scrollIntoViewIfNeeded();
    const clipped = await workspace.locator(".nurture-setup-fields").evaluate(element => {
      const edge = element.getBoundingClientRect().right;
      return [...element.querySelectorAll<HTMLElement>("*")].filter(child => child.getClientRects().length && child.getBoundingClientRect().right > edge + 1 && !child.closest('[hidden],details:not([open])'))
        .slice(0, 10).map(child => `${child.tagName}.${child.className}: ${Math.round(child.getBoundingClientRect().right - edge)}px`);
    });
    expect(clipped).toEqual([]);
    expect(await total.evaluate(input => ({ font: parseFloat(getComputedStyle(input).fontSize), height: input.getBoundingClientRect().height }))).toEqual({ font: 14, height: 36 });
    await page.screenshot({ path: test.info().outputPath(`nurture-setup-${viewport.width}.png`) });
  }
  await workspace.getByRole("tab", { name: "Hành vi", exact: true }).click();
  const frenzy = workspace.getByLabel("Bật Vuốt nhanh", { exact: true });
  const rate = workspace.getByLabel("Vuốt nhanh phần trăm", { exact: true });
  if (!await frenzy.isChecked()) { await frenzy.focus(); await page.keyboard.press("Space"); }
  await rate.fill("37");
  await frenzy.focus();
  await page.keyboard.press("Space");
  await expect(rate).toBeDisabled();
  await expect(rate).toHaveValue("37");
  await frenzy.focus();
  await page.keyboard.press("Space");
  await expect(rate).toBeEnabled();
  await expect(rate).toHaveValue("37");
  await workspace.getByRole("tab", { name: "AI", exact: true }).click();
  await expect(workspace.locator('input[list="riviu-comment-models"]')).toBeVisible();
  await workspace.getByRole("tab", { name: "Theo dõi", exact: true }).click();
  await workspace.getByRole("tab", { name: "Bình luận & chi phí AI", exact: true }).click();
  await page.screenshot({ path: test.info().outputPath("nurture-comment-tab.png") });
  await workspace.getByRole("tab", { name: "Hẹn giờ", exact: true }).click();
  await expect(workspace.getByRole("checkbox", { name: /Lịch tự chạy/ })).toBeVisible();
  await workspace.getByRole("button", { name: "+ Thêm khung giờ", exact: true }).click();
  await expect(workspace.getByLabel("Giờ bắt đầu khung 1", { exact: true })).toBeVisible();
  await workspace.getByRole("tab", { name: "Thiết lập", exact: true }).click();
  await workspace.getByRole("tab", { name: "Phiên nuôi", exact: true }).click();
  await expect(total).toHaveValue("75");
  await choose.click();
  await expect(machines.getByRole("checkbox", { checked: true })).toHaveCount(38);
  await picker.getByRole("searchbox", { name: "Tìm máy Nuôi TikTok" }).fill("38");
  await expect(machines.getByRole("checkbox")).toHaveCount(1);
  await machines.getByRole("checkbox").uncheck();
  await picker.getByRole("searchbox", { name: "Tìm máy Nuôi TikTok" }).fill("");
  await expect(machines.getByRole("checkbox", { checked: true })).toHaveCount(37);
  await picker.getByRole("button", { name: "Xong", exact: true }).click();
  await expect(workspace.locator(".nurture-scope-bar .nurture-count")).toHaveText("Đã chọn 37");
  await expect(scope).toHaveValue("explicit");
  await expect(scope.locator("option:checked")).toHaveText("37 máy đã chọn");
  const calls = await mockCommandCalls(page);
  expect(calls.filter(call => call.command === "nurture_start")).toEqual([]);
});
