import { test, expect } from "@playwright/test";
import { installTauriMock } from "./fixtures/tauriMock";

for (const width of [1440, 820]) test(`hover rail pins, groups fold, native dropdown and compact transfers at ${width}`, async ({ page }) => {
  await page.setViewportSize({width, height: 900});
  await installTauriMock(page, {androidRoster: true, fleetSize: 4});
  await page.addInitScript(() => {
    const w = window as unknown as { __POLISH_CALLS__: {cmd:string;args:Record<string,unknown>}[]; __TAURI_INTERNALS__: {invoke:(cmd:string,args?:Record<string,unknown>)=>Promise<unknown>} };
    const original = w.__TAURI_INTERNALS__.invoke;
    w.__POLISH_CALLS__=[];
    w.__TAURI_INTERNALS__.invoke=async(cmd,args={})=>{
      w.__POLISH_CALLS__.push({cmd,args});
      if(cmd==='plugin:dialog|open')return (args.options as {directory?:boolean}).directory ? 'C:/exports' : ['C:/photo.jpg','C:/clip.mp4'];
      if(cmd==='device_list_dir')return {entries:[{name:'Download',kind:'directory',size:0,modified:'2026-09-14 10:00',linkTarget:null},{name:'photo.jpg',kind:'file',size:12000,modified:'2026-09-14 10:00',linkTarget:null}],incomplete:null};
      if(cmd==='device_push_file')return String(args.remoteDir)+'/'+String(args.local).split('/').at(-1);
      if(cmd==='device_pull_path')return 'C:/exports/photo.jpg';
      if(['device_control_begin','device_control_end'].includes(cmd))return null;
      return original(cmd,args);
    };
  });
  await page.goto('/');
  const rail=page.getByRole('complementary',{name:'Thiết lập Control Center'});
  const panel=rail.locator('.rail-panel');
  await expect(panel).toHaveAttribute('aria-hidden','true');
  const before=await page.getByTestId('device-tile').first().boundingBox();
  await rail.getByRole('button',{name:'Hiện bảng Hiển thị'}).hover();
  await expect(panel).toHaveAttribute('aria-hidden','false');
  const after=await page.getByTestId('device-tile').first().boundingBox();
  expect(after!.x).toBe(before!.x);
  await rail.getByRole('button',{name:'Ghim bảng Hiển thị',exact:true}).click();
  await page.mouse.move(width-15, 10);
  await expect(rail).toHaveClass(/is-pinned/);
  await rail.locator('.rail-group-trigger').first().click();
  await expect(rail.getByRole('button',{name:/Chọn nhanh Máy/})).toHaveCount(4);
  await rail.locator('.rail-group-trigger').first().click();
  await expect(rail.getByRole('button',{name:/Chọn nhanh Máy/})).toHaveCount(0);
  await page.screenshot({path:test.info().outputPath('rail-pinned.png')});
  await page.reload();await expect(rail).toHaveClass(/is-pinned/);
  await rail.getByRole('button',{name:'Bỏ ghim bảng Hiển thị',exact:true}).click();
  await page.mouse.move(width-15, 10);
  await expect(panel).toHaveAttribute('aria-hidden','true');
  await page.getByTestId('device-tile').first().dblclick();
  const focus=page.locator('.device-floating-window');
  await focus.getByRole('button',{name:'PC → Điện thoại',exact:true}).click();
  const files=page.locator('.device-files');
  await expect(files).toHaveClass(/mode-upload/);
  await expect(files.getByText('photo.jpg, clip.mp4')).toBeVisible();
  await expect(files.getByRole('button',{name:'Lấy về máy tính'})).toHaveCount(0);
  await files.getByRole('button',{name:'Download',exact:true}).click();
  await files.getByRole('button',{name:'Đưa vào thư mục này',exact:true}).click();
  await expect(files.getByText('Đã đưa 2 tệp vào /sdcard/Download')).toBeVisible();
  await page.screenshot({path:test.info().outputPath('upload.png')});
  await files.getByRole('button',{name:'Đóng',exact:true}).click();
  await expect(files).toHaveCount(0);
  await expect(focus).toHaveCount(1);
  await focus.getByRole('button',{name:'Điện thoại → PC',exact:true}).click();
  await expect(files).toHaveClass(/mode-download/);
  await expect(files.getByRole('button',{name:'Đưa tệp vào đây'})).toHaveCount(0);
  await files.getByRole('checkbox',{name:'Chọn photo.jpg'}).check();
  await files.getByRole('button',{name:'Lấy về máy tính'}).click();
  await expect(files.getByText('Đã lấy 1 mục về C:/exports')).toBeVisible();
  const bounds=await files.boundingBox();expect(bounds!.height).toBeLessThan(700);expect(bounds!.width).toBeLessThanOrEqual(760);
  const row=files.locator('.device-files-list li').first();
  expect((await row.boundingBox())!.height).toBeLessThanOrEqual(38);
  const left=(await row.boundingBox())!.x;
  expect((await row.locator('.device-files-name').boundingBox())!.x-left).toBeLessThan(48);
  await page.screenshot({path:test.info().outputPath('download.png')});
  await page.keyboard.press('Escape');await expect(files).toHaveCount(0);await expect(focus).toHaveCount(1);
  await focus.getByRole('button',{name:'Đóng',exact:true}).click();
  await page.getByRole('button',{name:'Lượt chạy',exact:true}).click();
  const select=page.getByRole('combobox').first();
  expect(await select.evaluate(el=>getComputedStyle(el).appearance)).toBe('base-select');
  await select.click();
  expect(await select.evaluate(el=>el.matches(':open'))).toBe(true);
  expect(await select.evaluate(el=>getComputedStyle(el,'::picker(select)').borderRadius)).toBe('9px');
  await page.screenshot({path:test.info().outputPath('dropdown.png')});
  await page.keyboard.press('Escape');
  expect(await select.evaluate(el=>el.matches(':open'))).toBe(false);
  await page.getByRole('button',{name:'Tương tác',exact:true}).click();
  await expect(page.getByText('Nhập từ Google Sheet',{exact:true})).toHaveCount(0);
  const calls=await page.evaluate(()=>(window as unknown as {__POLISH_CALLS__:{cmd:string;args:Record<string,unknown>}[]}).__POLISH_CALLS__);
  const uploads=calls.filter(c=>c.cmd==='device_push_file');expect(uploads).toHaveLength(2);
  expect(uploads.every(c=>c.args.remoteDir==='/sdcard/Download')).toBe(true);
  expect(calls.filter(c=>c.cmd==='device_pull_path')).toHaveLength(1);
  expect(calls.some(c=>c.cmd==='interaction_import_sheet')).toBe(false);
});
