use riviu_core::{
    google_sheets::DeliveryReceipt, ipc_contract::*, operation::OperationDeviceLogEntry, *,
};
use ts_rs::TS;

fn main() -> anyhow::Result<()> {
    let output = std::env::args()
        .nth(1)
        .ok_or_else(|| anyhow::anyhow!("usage: export_ipc OUTPUT"))?;
    let config = ts_rs::Config::default().with_large_int("number");
    let declarations = [
        TraceArtifact::decl(&config),
        ui_automation::trace::DeviceTraceStep::decl(&config),
        OperationTrace::decl(&config),
        ConnectionKind::decl(&config),
        DeviceStatus::decl(&config),
        TileStreamState::decl(&config),
        DevicePlatform::decl(&config),
        DeviceInfo::decl(&config),
        StopDeviceResult::decl(&config),
        OperationStopResult::decl(&config),
        DeliveryReceipt::decl(&config),
        PublishSheetReadback::decl(&config),
        CapabilityEvidenceState::decl(&config),
        ActionCapability::decl(&config),
        DeviceActionCapabilities::decl(&config),
        OperationDeviceLogEntry::decl(&config),
        typesafe::Settings::decl(&config),
        typesafe::Support::decl(&config),
        typesafe::Verdict::decl(&config),
    ];
    let content = format!(
        "// Generated by cargo run -p riviu-core --example export_ipc. Do not edit.\n{}\n",
        declarations
            .iter()
            .map(|s| format!("export {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    let content = content
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    std::fs::write(output, content)?;
    Ok(())
}
