// Generated by cargo run -p riviu-core --example export_ipc. Do not edit.
export type TraceArtifact = { path: string, sha256: string, bytes: number, };
export type DeviceTraceStep = { runId: string, deviceId: string, assignmentId: string | null, sessionId: string, sequence: number, observedAt: string, elapsedMs: number, action: string,
/**
 * A transport acknowledgement is never a business postcondition.
 */
state: string, error: string | null, hierarchyGeneration: number | null, hierarchy: TraceArtifact | null,
/**
 * The currently cached stream frame, for diagnosis only; freshness is unverified.
 */
image: TraceArtifact | null, };
export type OperationTrace = { runId: string, deviceId: string, sessionId: string | null, observedAt: string, steps: Array<OperationDeviceLogEntry>, artifacts: Array<TraceArtifact>, observations: Array<DeviceTraceStep>, };
export type ConnectionKind = "usb" | "wifi" | "mock";
export type DeviceStatus = "disconnected" | "pairing" | "connected" | "preparing" | "ready" | "busy" | "error";
export type TileStreamState = "live" | "sampling" | "parked" | "stale" | "error";
export type DevicePlatform = "ios" | "android";
export type DeviceInfo = { udid: string, name: string, model: string, platform: DevicePlatform,
/**
 * The OS release, as the platform words it: `16.7.15` on iOS, `15` on
 * Android. Read with [`Self::platform`], never alone — it used to be called
 * `ios_version` and the UI printed a hardcoded "iOS" beside it.
 */
osVersion: string, connection: ConnectionKind, status: DeviceStatus, battery: number | null, wdaReady: boolean, wdaExpiresAt: string | null, streamUrl: string | null, tileStreamState: TileStreamState, lastError: string | null, };
export type StopDeviceResult = { udid: string, closed: boolean, message: string, };
export type OperationStopResult = { operationId: string, state: string, devices: Array<StopDeviceResult>, stopMarker: string | null, };
export type DeliveryReceipt = { publicationId: string, row: number, revision: number, reportingEpoch: string, postUrl: string, duplicate: boolean, };
export type PublishSheetReadback = { assignmentId: string, url: string, range: string, revision: number, epoch: string, checkedAt: string, receipt: DeliveryReceipt, };
export type CapabilityEvidenceState = "measured" | "runtimeProofRequired" | "unsupported" | "deviceNotReady";
export type ActionCapability = { action: string, state: CapabilityEvidenceState, reason: string, };
export type DeviceActionCapabilities = { udid: string, package: string, version: string, locale: string, actions: Array<ActionCapability>, };
export type OperationDeviceLogEntry = { id: string, at: string | null, action: string, state: string, text: string | null, detail: string | null, };
export type TypeSafeSettings = { revision: number, enabled: boolean, hasApiKey: boolean, };
export type TypeSafeSupport = "supported" | "contradicted" | "insufficient";
export type TypeSafeVerdict = { support: TypeSafeSupport, confidence: number, probabilities: { [key in string]: number }, model: string, inputTokens: number, outputTokens: number, elapsedMs: number, };
